### PR TITLE
Token Allocation BN support

### PR DESCRIPTION
**Pull request by Da-Colon**
Description
Updates to fully support BigNumbers smoothly for the Token Allocations input.

Notes
- Follows the same patterns as #475 

Testing
Create a DAO -> Essentials -> Choose Governance (1:1 Token Voting) -> Treasury and Governance Token

- Token Allocation Amount: User should be able to type Large Number and decimals up to 18

- Token Allocation Amount: User should only type numbers
-> Governance Config -> Deploy

- Token Supply Error should still be able to calculate if Token Allocations is greater than Token Supply

User should be able to Deploy a new DAO with correct allocation (see Governance)

## Screenshots (if applicable)
image

### CODE REVIEW

**Review by Da-Colon — COMMENTED** [review]
Similar Changes to #475. 2 of set of 3

**Comment by adamgall** [comment]
@Da-Colon if this PR relies on another one to be merged first, safest to put this in draft status for now, and make it clear at the top of the first comment that this relies on another PR first.

**Review by SudoPumpkin — COMMENTED** [review]
Here's an example of the desired validation in a screenshot for others testing this change:
image

This test case seems to work as intended yet the below behavioral observation is slightly cumbersome. 

**Observed Usability Issue**
@Da-Colon Let me know if you want me to write this up somewhere else, I thought about tossing it in the public 'Issues' thread but it doesn't occur on app.dev yet. It only occurs in PRs '476' and '477'. 
_Issue_
The user can not clear the 'Amount' field of the 'Treasury and Governance Token' step. On PR '476' it keeps the first digit after input.
_Example:_ 

https://user-images.githubusercontent.com/86701852/188230811-3d68c17f-849e-4242-82c3-9ed92327e94f.mp4


- User inputs '570'
- User backspaces in the 'Amount' field
- The amount field now keeps '5' forever and spit out the below console error:
> Uncaught Error: invalid decimal value (argument="value", value="", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at e.value (index.ts:269:28)
    at e.value (index.ts:281:20)
    at e.value (index.ts:285:21)
    at h (fixednumber.ts:76:16)
    at Module.u (index.ts:80:12)
    at hi (crypto.ts:11:10)
    at onChange (TokenAllocationInput.tsx:42:33)
    at Object.ze (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
 
Work around is to just 'Remove' allocation and start again.

On PR '477' the mighty '0' remains dominate on user attempt to clear the same field.

**Comment by Da-Colon** [comment]
Yes I'll get this updated. I had fixed this issue in the Supply and need to spread that change across these PRs

**Review by adamgall — APPROVED** [review]
Pretty straightforward, LGTM

**Review by tbwebb22 — APPROVED** [review]
Running through the test case, everything worked for me.
Code looks good as well

**Pull request merged**
