### PR TITLE
Reuse account display name

### PR DESCRIPTION
**Pull request by adamgall**
The issue is that each time the menu is opened, if the connected account has an ENS name, there's a quick flash as the address turns into the ens name, _every time the menu is opened_.

- @Da-Colon ur probably gonna yell at me, but first thing in this PR is that I changed some of the initial values of Web3Provider object from `null` to `undefined` (for better compatibility with how the rest of the app is set up)
- Next I added the "account display name" to global `useBlockchainData`, so that we don't have to fetch it each time we want to show it (for example, like _each time_ the menu is opened).
- Finally I used that thang in the Menu

### CODE REVIEW

**Comment by Da-Colon** [comment]
@adamgall you are right, here it comes 😠 lol. 

So first my reasoning for `null` versus `undefined`. 

- undefined for me is a value that after initialization, its unknown whether be set or not
- null being used for situation ways where the state of something is more intentional (set or not set).

> (for better compatibility with how the rest of the app is set up)
This package is meant to be more universal.

**Comment by adamgall** [comment]
> @adamgall you are right, here it comes 😠 lol. 
> 
> 
> 
> So first my reasoning for `null` versus `undefined`. 
> 
> 
> 
> - undefined for me is a value that after initialization, its unknown whether be set or not
> 
> - null being used for situation ways where the state of something is more intentional (set or not set).
> 
> 
> 
> So for in this case, account is either connected or not connect. we will always be sure that is will be one or the other.
> 
> 
> 
> > (for better compatibility with how the rest of the app is set up)
> 
> 
> 
> This package is meant to be more universal. 

I agree completely with the points you're making, and argue that this PR puts things back into that pattern.

**Comment by adamgall** [comment]
Eh, disregard my last comment. I need to think about this more.

For the sake of exercise, if you have time, pull this branch down and make those things `null` again, and see how much that complicates what I was trying to do with this PR.

**Comment by adamgall** [comment]
@Da-Colon i've merged #354 into this branch. so it should pass your review now.

**Review by Da-Colon — APPROVED** [review]
@adamgall LGTM thanks for hearing me out.

**Pull request merged**
