### PR TITLE
Production push

### PR DESCRIPTION
**Pull request by adamgall**
Includes the following work:
- PR #1397
  - closes Issue #1396
- PR #1410
  - closes Issue #1409
- PR #1416 
  - closes Issue #1384
- PR #1382 
  - closes Issue  #1362 
- PR #1417 
  - closes Issue #1411

### CODE REVIEW

**Review by azadikoff — APPROVED** [review]
I'm not too sure what to look for, but I poked around the site and didn't find any issues.

**Review by nicolaus-sherrill — COMMENTED** [review]
Token prices are not showing up in Decent DAO's treasury. Treasury balance is showing $0 and all tokens in the treasury show a $0 value.

Testing:
Firefox on MacOS Sonoma.

**Comment by adamgall** [comment]
@nicolaus-sherrill thanks for the comments!

as @mudrila said, please share some more details:
- what is the exact URL you're looking at?
  - this should include the specific Safe
- do you have a wallet connected and is that wallet on the intended network?

**Comment by nicolaus-sherrill** [comment]
@adamgall @mudrila 

Here is a screenshot showing what I'm seeing. Wallet is connected and on Mainnet.

URL:[Decent DAO Treasury](https://app.fractalframework.xyz/daos/0xD26c85D435F02DaB8B220cd4D2d398f6f646e235/treasury)

Screenshot 2024-03-08 at 11 07 28 AM

**Comment by adamgall** [comment]
> @adamgall @mudrila
> 
> Here is a screenshot showing what I'm seeing. Wallet is connected and on Mainnet.
> 
> URL:[Decent DAO Treasury](https://app.fractalframework.xyz/daos/0xD26c85D435F02DaB8B220cd4D2d398f6f646e235/treasury)
> 
> Screenshot 2024-03-08 at 11 07 28 AM

You're on the production URL, which doesn't include the changes that we're proposing in this PR. The idea is that we'd like to get this code _into_ production, but it's not there yet.

Use the ["Preview Deploy" link](https://deploy-preview-1420.app.fractalframework.xyz/) from the [Netlify comment above](https://github.com/decent-dao/fractal-interface/pull/1420#issuecomment-1984645712), to access a URL that includes the changes within this Pull Request:

**Review by nicolaus-sherrill — APPROVED** [review]

**Review by Da-Colon — APPROVED** [review]
Ship it

**Pull request merged**
