### PR TITLE
V1 | Header Clean up

### PR DESCRIPTION
**Pull request by Da-Colon**
## Description
Cleans up and updates header with changes since implementation.

### Favorites
- Switches out Icon
- adds DownArrow
### Account Display (connected) Menu Button
- Allow for Avatar to properly size
- Centers avatar
### Wallet Menu
- overrides chakra-ui default padding on menu item
- adds a width and text overflow to handle large ENS names
- fixes hover and padding on menu items button component

## Issue / Notion doc (if applicable)

closes https://github.com/decent-dao/fractal-interface/issues/655

## Screenshots (if applicable)
image

### CODE REVIEW

**Review by herbig — APPROVED** [review]
🚀

**Comment by herbig** [comment]
@Da-Colon the FAQ button test failed on the homepage for some reason... rerunning with a merge, but seems pretty weird

**Comment by Da-Colon** [comment]
yeah I'm currently testing locally to fix.

**Comment by Da-Colon** [comment]
@herbig I set `fullyParallel` to false. best case this will help the test to run separately without any problems of running to quickly. worst case, CLI is only using a single worker, so probably doesn't need to be true anyway

**Pull request merged**
