### PR TITLE
Moar bug fixes

### PR DESCRIPTION
**Pull request by herbig**
## Issue / Notion doc (if applicable)

- closes https://github.com/decent-dao/fractal-interface/issues/829
- removes isLazy from account and favorites menus
- disables the WARNING message, for now

## Testing

- Test opening closing Account / Favorites, you should no longer see ENS names loading
- Test that the Audit WARNING message no longer appears (use Incognito mode)
- Test Proposal Creation button is now disabled on page start, and if there is no target / function input

### CODE REVIEW

**Review by mobiusTripper-crypto — APPROVED** [review]
looks good

**Review by tbwebb22 — COMMENTED** [review]
I'm still seeing the Create Proposal button appear before I've entered in all the necessary params

image

**Comment by tbwebb22** [comment]
> I'm still seeing the Create Proposal button appear before I've entered in all the necessary params
> 
> image

Ohh disregard, just realized this is because some function calls take no params

**Review by tbwebb22 — APPROVED** [review]
LGTM

**Pull request merged**
