### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by mudrila**
## Description

This PR translates application to Ukrainian following our script - https://github.com/decent-dao/fractal-interface/blob/develop/TRANSLATIONS.md

## Notes

n/a

## Issue / Notion doc (if applicable)

n/a

## Testing

1. Open the app
2. Switch the language to Ukrainian
3. Verify that you see Ukrainian language
4. Thoroughly walk through the app - check that all the strings are translated (some names like "Fractal", "DAO", "NFT", "Gnosis", "Safe" are not translatable).
5. Glory to Ukraine! Slava Ukraine!

## Screenshots (if applicable)
Знімок екрана 2022-12-14 о 20 06 57
Знімок екрана 2022-12-14 о 20 10 01

### CODE REVIEW

**Review by Da-Colon — APPROVED** [review]
I'll approve, but is this PR going to be waiting on the current open PR updates?

**Comment by mobiusTripper-crypto** [comment]
I found a couple of small things which I do not have anything do to with your translations, but were not apparent until I could turn a legit one on. I'll make issues for them. So Thumbs Up!! looks awesome.

**Review by mobiusTripper-crypto — APPROVED** [review]
Looks great!

**Comment by herbig** [comment]
> I'll approve, but is this PR going to be waiting on the current open PR updates?

I think we can merge this in, then after all the other updates are done and copy changes are made we can easily export the English / Ukrainian comparisons to CSV again and make updates

**Pull request merged**
