### PR TITLE
Remove Background Glow

### LINKED ISSUE #1424: Eliminate the yellow radial gradient background from existence
Please update the background of the app by removing the yellow radial gradient BG and changing the subtle gradient background to a solid color #262521 (which is chocolate 700 currently)

image

### PR DESCRIPTION
**Pull request by Da-Colon**
This PR updates the decent UI version. This version removes the background gold glow

## Screenshot
localhost_3000_(Desktop)

Closes #1424

### CODE REVIEW

**Review by adamgall — APPROVED** [review]
LGTM, shipit

**Comment by xraystyle1980** [comment]
Can you make the background a solid color? #262521 (#262521 should be the same as chocolate 700 in the current color palette)

**Review by adamgall — CHANGES_REQUESTED** [review]
DON'T SHIPIT!

**Review by adamgall — APPROVED** [review]
better now, SHIPIT

**Pull request merged**
