### PR TITLE
Add Custom Nonce; BugFix BigNumberInput

### LINKED ISSUE #1207: Proposal Templates Should Allow Variable Eth Value
### Overview

We don't allow an input field for Eth value, this should be able to be variable, e.g. wrap / unwrap WETH

https://goerli.etherscan.io/token/0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6

Screenshot 2023-06-13 at 12 07 11 PM

### Additional Info

_No response_

### Version

Dev (app.dev.fractalframework.xyz/)

### LINKED ISSUE #1217: Bug: BigNumberInput won't allow decimal point
### Overview

This seems to have been broken for quite a quite.

I attempted to fix this in commit 9334c8df, but reverted that change as it broke the BigNumberInput default values.

This is a tricky one, as the value the input is reactive to is a BigNumber.  Likely we will need to change that to a string.

### Additional Info

_No response_

### Version

Dev (app.dev.fractalframework.xyz/)

### PR DESCRIPTION
**Pull request by Da-Colon**
## Issue / Notion doc (if applicable)

Closes #1217

### CODE REVIEW

**Review by herbig — CHANGES_REQUESTED** [review]
@Da-Colon I'm not able to input decimal place in Send Assets, also this change breaks default numbers for BigNumberInput:

Screenshot 2023-07-07 at 10 53 31 AM

**Comment by Da-Colon** [comment]
> @Da-Colon I'm not able to input decimal place in Send Assets, also this change breaks default numbers for BigNumberInput:
> 
> Screenshot 2023-07-07 at 10 53 31 AM

dang okay, I'll make some tweaks. I'll reping when ready to test again

**Comment by Da-Colon** [comment]
@herbig should be good to good now. reverted my changes and took another look and fixed the actual issue in the useEffect. Re-tested SendAssets and works as expected now

**Comment by Da-Colon** [comment]
@herbig wierd works for me?

**Comment by Da-Colon** [comment]
@herbig what token are you trying to transfer. could be another issue in send assets and the decimal places

**Review by herbig — APPROVED** [review]
🚢

**Pull request merged**
