### PR TITLE
BugFix | Clean DAO data when not viewing DAO

### LINKED ISSUE #793: Side NavItems show on Welcome screen.
To Reproduce:
- Load in a DAO
- Click on Fractal F logo (top-right)

Image

### PR DESCRIPTION
**Pull request by Da-Colon**
## Description
Added a useEffect to clear state when not within DAO.

## Notes
- I tried a few different approaches here. I would prefer to have `DAOController` make this update, but because of how React Route is works. params of nested routes won't be recongnized by parent. So moving `useDAOController` isn't really an option and doesn't work. 
- There isn't any real way (and you shouldn't) update state on unMount.
- I believe I had a version of this before and had deleted it as it was causing some issues with loading. This version using routeMatch to check if state should be reset. instead of data from state.

## Issue / Notion doc (if applicable)
Closes #793

## Testing
Go to all the different routes and back home again. make sure state is changing correctly

### CODE REVIEW

**Comment by herbig** [comment]
Not sure what's up, but the deploy preview for this just hangs on a DAO homepage

https://deploy-preview-809--fractal-framework-interface-dev.netlify.app/#/daos/0xbFC43fba83971596709cA0f66B1C54B89aad7551

**Comment by Da-Colon** [comment]
> Not sure what's up, but the deploy preview for this just hangs on a DAO homepage
> 
> https://deploy-preview-809--fractal-framework-interface-dev.netlify.app/#/daos/0xbFC43fba83971596709cA0f66B1C54B89aad7551

almost went down a rabbit hole. is your account connected? if not that would likely cause that.

**Comment by herbig** [comment]
> > Not sure what's up, but the deploy preview for this just hangs on a DAO homepage
> > https://deploy-preview-809--fractal-framework-interface-dev.netlify.app/#/daos/0xbFC43fba83971596709cA0f66B1C54B89aad7551
> 
> almost went down a rabbit hole. is your account connected? if not that would likely cause that.

🤦

**Review by herbig — APPROVED** [review]
Looks good, and works as expected!

**Pull request merged**
