### PR TITLE
Update | No account DAO viewing

### PR DESCRIPTION
**Pull request by Da-Colon**

### CODE REVIEW

**Review by mobiusTripper-crypto — APPROVED** [review]
looks good to me, but I did find this, when there are no proposals, the Create Proposal button works here. Seems like it should be hidden when not connected

image

**Comment by Da-Colon** [comment]
> looks good to me, but I did find this, when there are no proposals, the Create Proposal button works here. Seems like it should be hidden when not connected
> 
> image

o darn missed this one good catch.

**Review by christopherdancy — APPROVED** [review]
This looks good. However, I am a tad confused on how we will alert users. It seems like they may be confused if not prompted to connect.

**Comment by Da-Colon** [comment]
> This looks good. However, I am a tad confused on how we will alert users. It seems like they may be confused if not prompted to connect.

Since we no longer 'require' to be connected. I don't think we should prompt a user on DAO screens. We are still covering the Create DAO workflow I believe. but otherwise. they are just more or less viewing a DAO

**Review by herbig — APPROVED** [review]

**Pull request merged**
