### PR TITLE
Nav tooltips appear under the NavBar

### PR DESCRIPTION
**Pull request by mobiusTripper-crypto**
## Description
Display order of the GridItems in App.txs doesn't allow for popover items to display in the correct z-index order. Change the order so both the tooltip and language menu display correctly.

## Screenshots (if applicable)
image

### CODE REVIEW

**Review by herbig — APPROVED** [review]
🛳🛳🛳

**Comment by Da-Colon** [comment]
Hmmm I had tested and thought just adding the Popover was fine?

**Comment by mobiusTripper-crypto** [comment]
@Da-Colon but the order of the GridItems on app.tsx is what keeps everything in the correct order, somehow on your merge they got changed back to where they didn't work. I don't think using z-index in this situation is reliable.

**Comment by Da-Colon** [comment]
I guess I'm confused on how order of gridItems is related to Zindex of the tooltips? if this works not a big deal lets ship, I can ask questions later.

**Review by Da-Colon — APPROVED** [review]

**Comment by mobiusTripper-crypto** [comment]
In this case I believe the 'stacking context', in conjuntion with setting the transitions and position properties overrides z-index. So with the conflict in the Language Menu and Proposal list. Some of the items in the proposal list have transitions (can't recall the element off the top of my head not), and some have relative position set. Both of those properties will result in them being displayed in the order in which they are added to the DOM. By switching the order in app.tsx, then the menu is in the DOM first. I'm pretty sure zindex only really works in side a single stacking context, and in this case `nav`, `header`, and `toolbar` are all in different contexts ... the same problem occurred with the favorites menu actually.

**Comment by mobiusTripper-crypto** [comment]
@Da-Colon I didn't address your actual question. which is why the tooltip is under the sidebar ... which I think we could discuss later, becuase my brain hurts from thinking about zindex

**Pull request merged**
